CXX = g++-4.3
CXXFLAGS = -Wall -O0 -std=c++0x

all: rvalue variadic_templates
	./rvalue
	./variadic_templates

clean:
	rm -f rvalue variadic_templates

rvalue: rvalue.cpp
variadic_templates: variadic_templates.cpp

