/*
 * DistanceEditorPanel.java
 *
 * Created on September 21, 2005, 9:34 PM
 */

package pigeon.view;

import java.awt.Component;
import java.util.Map;
import java.util.SortedMap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import pigeon.model.Distance;
import pigeon.model.Member;
import pigeon.model.Racepoint;

/**
 *
 * @author  pauldoo
 */
public class DistanceEditorPanel<Subject, Target> extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 42L;
    
    public static void editMemberDistances(Component parent, Member member, SortedMap<Racepoint, Distance> distances) {
        DistanceEditorPanel<Member, Racepoint> panel = new DistanceEditorPanel<Member, Racepoint>(member, distances);
        JOptionPane.showMessageDialog(parent, panel, "Distances", JOptionPane.PLAIN_MESSAGE);
    }

    public static void editRacepointDistances(Component parent, Racepoint racepoint, SortedMap<Member, Distance> distances) {
        DistanceEditorPanel<Racepoint, Member> panel = new DistanceEditorPanel<Racepoint, Member>(racepoint, distances);
        JOptionPane.showMessageDialog(parent, panel, "Distances", JOptionPane.PLAIN_MESSAGE);
    }
    
    /** Creates new form DistanceEditorPanel */
    public DistanceEditorPanel(Subject subject, SortedMap<Target, Distance> distances) {
        initComponents();
        titleLabel.setText(titleLabel.getText() + " " + subject.toString());
        for (Map.Entry<Target, Distance> entry: distances.entrySet()) {
            this.add( new JLabel(entry.getKey().toString()) );
            this.add( new JLabel(entry.getValue().toString() ));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        titleLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        titleLabel.setText("Distances For");
        add(titleLabel, new java.awt.GridBagConstraints());

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
}
