/*
 * MemberInfo.java
 *
 * Created on 06 September 2005, 20:30
 */

package pigeon.view;

import java.awt.Component;
import javax.swing.JOptionPane;
import pigeon.model.Member;

/**
 *
 * @author  Sarah
 */
public class MemberInfo extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 42L;

    /** Creates new form MemberInfo */
    public MemberInfo(Member member, boolean editable) {
        initComponents();
        nameText.setText( member.getName() );
        nameText.setEditable( editable );
        addressText.setText( member.getAddress() );
        addressText.setEditable( editable );
        telephoneText.setText( member.getTelephone() );
        telephoneText.setEditable( editable );
        ringNumberFromText.setText( member.getRingNumberFrom() );
        ringNumberFromText.setEditable( editable );
        ringNumberToText.setText( member.getRingNumberTo() );
        ringNumberToText.setEditable( editable );
        SHUNumberText.setText(member.getSHUNumber());
        SHUNumberText.setEditable(editable);
    }
    
    private void updateMemberObject(Member member) {
        member.setName( nameText.getText() );
        member.setAddress( addressText.getText() );
        member.setTelephone( telephoneText.getText() );
        member.setRingNumberFrom( ringNumberFromText.getText() );
        member.setRingNumberTo( ringNumberToText.getText() );
        member.setSHUNumber(SHUNumberText.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressScrollPane = new javax.swing.JScrollPane();
        addressText = new javax.swing.JTextArea();
        telephoneLabel = new javax.swing.JLabel();
        telephoneText = new javax.swing.JTextField();
        ringNumberLabel = new javax.swing.JLabel();
        ringNumberFromLabel = new javax.swing.JLabel();
        ringNumberFromText = new javax.swing.JTextField();
        ringNumberToLabel = new javax.swing.JLabel();
        ringNumberToText = new javax.swing.JTextField();
        memberInformationLabel = new javax.swing.JLabel();
        SHUNumberLabel = new javax.swing.JLabel();
        SHUNumberText = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("Member Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nameLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(nameText, gridBagConstraints);

        addressLabel.setText("Contact Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(addressLabel, gridBagConstraints);

        addressText.setRows(5);
        addressScrollPane.setViewportView(addressText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(addressScrollPane, gridBagConstraints);

        telephoneLabel.setText("Telephone No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(telephoneLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(telephoneText, gridBagConstraints);

        ringNumberLabel.setText("Ring Numbers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(ringNumberLabel, gridBagConstraints);

        ringNumberFromLabel.setText("From");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(ringNumberFromLabel, gridBagConstraints);

        ringNumberFromText.setColumns(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(ringNumberFromText, gridBagConstraints);

        ringNumberToLabel.setText("To");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(ringNumberToLabel, gridBagConstraints);

        ringNumberToText.setColumns(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(ringNumberToText, gridBagConstraints);

        memberInformationLabel.setText("Member Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(memberInformationLabel, gridBagConstraints);

        SHUNumberLabel.setText("SHU Registration No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(SHUNumberLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(SHUNumberText, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SHUNumberLabel;
    private javax.swing.JTextField SHUNumberText;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JScrollPane addressScrollPane;
    private javax.swing.JTextArea addressText;
    private javax.swing.JLabel memberInformationLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel ringNumberFromLabel;
    private javax.swing.JTextField ringNumberFromText;
    private javax.swing.JLabel ringNumberLabel;
    private javax.swing.JLabel ringNumberToLabel;
    private javax.swing.JTextField ringNumberToText;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneText;
    // End of variables declaration//GEN-END:variables
    
    public static void editMember(Component parent, Member member) {
        MemberInfo panel = new MemberInfo(member, true);
        JOptionPane.showMessageDialog(parent, panel, "Member Information", JOptionPane.PLAIN_MESSAGE);
        panel.updateMemberObject(member);
    }
    
    public static Member createMember(Component parent) {
        Member member = new Member();
        editMember(parent, member);
        return member;
    }
}
